name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Ensure it matches the version in your Dockerfile

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1  # Update with your AWS region

    - name: Build and tag Docker image
      run: |
        # Define ECR repository name and image URI
        ECR_REPOSITORY= 	hola-mundo-repo   # Replace with your ECR repository name
        IMAGE_TAG=latest                    # You can use a dynamic tag such as Git commit hash as well
        IMAGE_URI=778425189746.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG  # Replace with your AWS account ID and region

        # Build the Docker image
        docker build -t $IMAGE_URI .

    - name: Push Docker image to ECR
      run: |
        # Push the image to ECR
        docker push $IMAGE_URI

    - name: Post-build cleanup
      run: |
        # Optionally remove local Docker images to save space
        docker rmi $IMAGE_URI || true
